name: ecoheroes
description: Ecoheroes Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+12

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  pull_to_refresh: ^1.5.8
  badges: ^1.1.1

  ##firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.0
  flutter_facebook_auth: ^0.2.4
  sign_in_with_apple: ^2.5.2
  google_sign_in: ^4.5.1
  firebase_image: ^0.2.0
  flutter_image_compress: ^0.7.0
  
  image_picker: ^0.6.7
  http: ^0.12.1
  flutter_widget_from_html: ^0.3.3+4
  cached_video_player: ^1.0.2+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/ic_launcher_round.png
  adaptive_icon_foreground: assets/icon/ic_launcher_foreground.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima-nova-thin.otf
          weight: 300
        - asset: assets/fonts/proxima-nova-regular.otf
          weight: 500
        - asset: assets/fonts/proxima-nova-bold.otf
          weight: 700
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: CustomIcon2
      fonts:
        - asset: assets/fonts/CustomIcon2.ttf
