import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

Widget html = HtmlWidget(
  """
<div style='text-align: justify;'>
<p style='font-size: 30px'>Terminos y Condiciones Generales</p>
<p>El acceso y uso de la aplicaci&oacute;n m&oacute;vil EcoHeroes (en adelante, indistintamente, la &ldquo;App&rdquo;) se rige por los T&eacute;rminos y Condiciones Generales (en adelante, indistintamente, &ldquo;T&eacute;rminos y Condiciones&rdquo;) descritos a continuaci&oacute;n, as&iacute; como por la legislaci&oacute;n vigente en la Rep&uacute;blica de Chile. En consecuencia, todas las visitas, operaciones y todos los contratos y transacciones que se realicen por medio de esta App, como asimismo sus efectos jur&iacute;dicos, quedar&aacute;n regidos por estas reglas y sometidas a esa legislaci&oacute;n. Los presentes T&eacute;rminos y Condiciones Generales ser&aacute;n aplicables a todos y cada uno de los usuarios de la App.</p>
<p>Leyendo y conociendo estos T&eacute;rminos y Condiciones, podr&aacute; hacer un mejor uso de la App, pudiendo ejercer adecuadamente sus derechos y cumplir sus obligaciones como usuario. Por ello, le sugerimos leer detalladamente estos T&eacute;rminos y Condiciones, imprimirlos y conservar una copia impresa de los mismos.</p>
<strong>A. Acerca de EcoHeroes</strong>
<p>EcoHeroes pertenece a Comercializadora Brera SpA, RUT N&ordm; 76.530.563-2, sociedad por acciones constituida y domiciliada en Chile (en adelante &ldquo;la Empresa&rdquo; o &ldquo;Brera&rdquo;). Se encuentra ubicada en Avenida La Dehesa 1822, oficina 701, comuna de Lo Barnechea, y el tel&eacute;fono de contacto es (+56-2) 32649223 o el correo electr&oacute;nico contacto@ecoheroes.cl. El representante legal de Comercializadora Brera SpA es Tom&aacute;s Alonso de Frutos.</p>
<p>EcoHeroes es una aplicaci&oacute;n para tel&eacute;fonos m&oacute;viles &ldquo;smartphone&rdquo; que mediante la realizaci&oacute;n de diferentes actividades o desaf&iacute;os relacionados al cuidado del medio ambiente, por parte de los usuarios, estos son recompensados mediante cupones de descuentos, puntos de canje o cupones de donaciones de &aacute;rboles, los cuales son patrocinados por parte de distintas empresas y clientes de Comercializadora Brera SpA, que est&aacute;n interesadas en los contenidos de marketing y publicidad ofrecidos por EcoHeroes.</p>
<strong>B. Funcionamiento de EcoHeroes.</strong>
<p>Para poder utilizar la App s&oacute;lo es necesario que los usuarios tengan un smartphone, con sistema operativo iOS o Android, conexi&oacute;n a internet, y ser mayor de 18 a&ntilde;os. EcoHeroes se reserva el derecho de eliminar las cuentas de usuarios menores de 18 a&ntilde;os y de aquellos que otorguen informaci&oacute;n falsa en el registro.</p>
<p>Se trata de una aplicaci&oacute;n gratuita que puede ser descargada desde el App Store o Google Play, seg&uacute;n corresponda.</p>
<p>La aplicaci&oacute;n m&oacute;vil permite a todo usuarios realizar cualquiera de los 12 tipos de desaf&iacute;os que son ofrecidos en la App:</p>
<ol>
<li>Plantar un &aacute;rbol en el patio de tu hogar</li>
<li>Sembrar una planta</li>
<li>Crear un ecoladrillo</li>
<li>Realizar un Instagram Live sobre reciclaje, medio ambiente o cambio clim&aacute;tico.</li>
<li>Separar los residuos del hogar</li>
<li>Crear un art&iacute;culo verde para el blog de EcoHeroes</li>
<li>Cocinar una comida vegana</li>
<li>Crear una receta de comida vegana</li>
<li>Crear una obra de arte reciclado</li>
<li>Responder una trivia</li>
<li>Responder una encuesta</li>
<li>Reciclar en un punto verde</li>
</ol>
<p>La correcta realizaci&oacute;n de los desaf&iacute;os otorga recompensas a los usuarios que las realizan, obteniendo en todos los desaf&iacute;os la acumulaci&oacute;n de &ldquo;hojas de experiencia&rdquo;:</p>
<ol type="a">
<li>Hojas de experiencia (): Por realizar correctamente cualquier tipo de desaf&iacute;o, el usuario siempre ganar&aacute; &ldquo;hojas de experiencia&rdquo;. A medida que el usuario acumule m&aacute;s &ldquo;hojas&rdquo;, podr&aacute; utilizarlas para los sorteos o canjes de productos ecofriendly de empresas asociadas con EcoHeroes, dependiendo del nivel y acumulacion de hojas de canje de cada usuario. Cada desaf&iacute;o otorgar&aacute; entre 5 y 25 hojas de experiencia, asignadas seg&uacute;n su nivel de complejidad.</li>
<p>Adicionalmente, los usuarios obtendr&aacute;n una de las siguientes tres opciones de recompensas:</p>
<li>Cupones de descuento: Existen 2 tipos de cupones de descuento canjeables en la empresa que patrocina cada desaf&iacute;o. Pueden ser cupones valorados en montos en pesos, y en otros casos, cupones con un descuento expresados de forma porcentual. El usuario encontrar&aacute; en el s&iacute;mbolo &ldquo;?&rdquo; inclu&iacute;do en cada desaf&iacute;o, las respectivas condiciones de cada uno de los cupones para poder ser canjeados correctamente.</li>
<li>Cupones de plantaci&oacute;n de &aacute;rboles: Tenemos una serie de desaf&iacute;os que al ser realizados correctamente por los usuarios, estos recibir&aacute;n como recompensa un cup&oacute;n con un c&oacute;digo que ser&aacute; canjeable por cierta cantidad de &aacute;rboles, definido seg&uacute;n la dificultad del desaf&iacute;o y patrocinio de la empresa, para plantar a trav&eacute;s de la ONG One Tree Planted en su p&aacute;gina web.</li>
<li>Puntos de canje: Algunos desaf&iacute;os realizados ser&aacute;n recompensadas con puntos, los que luego el usuario podr&aacute; canjearlos por diversas giftcards, productos, servicios y experiencias de varias empresas, todas estas ofrecidas en la p&aacute;gina web de nuestra alianza con PuntosPoint.</li>
</ol>
<p>Si el usuario acepta un desaf&iacute;o, al cual ha postulado y se le ha ofrecido previamente por EcoHeroes, &eacute;ste se bloquea para los dem&aacute;s usuarios. El usuario tendr&aacute; un plazo de 7 d&iacute;as corridos para completar el desaf&iacute;o. Una vez cumplido ese plazo y si el usuario no finaliz&oacute; la tarea, &eacute;sta se desbloquear&aacute; y se ofrecer&aacute; a otros usuarios.</p>
<p>El usuario declara expresamente que reconoce y entiende que:</p>
<p>1.- Todo desaf&iacute;o ofrecido se trata de un encargo o mandato por el cual EcoHeroes conf&iacute;a la gesti&oacute;n de uno o m&aacute;s desaf&iacute;os al usuario, que se hace cargo de ellos, y por el cual EcoHeroes entrega una recompensa al usuario.</p>
<p>2.- El usuario no es un trabajador de EcoHeroes, ni de Comercializadora Brera SpA, ni del cliente de Brera en relaci&oacute;n al cual se desarrolla una determinada tarea o desaf&iacute;o.</p>
<p>3.- Los desaf&iacute;os que EcoHeroes encarga al usuario no son un trabajo remunerado.</p>
<p>4.- Las relaciones entre el usuario y EcoHeroes no se rigen por el C&oacute;digo del Trabajo, sino por el C&oacute;digo Civil, como cualquier prestaci&oacute;n de servicios civiles.</p>
<p>El usuario declara y entiende que EcoHeroes no asegura una cantidad m&iacute;nima de desaf&iacute;os encargados al usuario ni tampoco periodicidad en los desaf&iacute;os, ya que &eacute;stos se asignan seg&uacute;n orden cronol&oacute;gico de solicitud del usuario, a completa discrecionalidad de EcoHeroes.</p>
<strong>C. Sobre los servicios de geolocalizaci&oacute;n.</strong>
<p>Es requisito que los EcoHeroes tengan activado el servicio de localizaci&oacute;n de sus tel&eacute;fonos smartphone para poder realizar los desaf&iacute;os. De esta forma, la App podr&aacute; mostrar los desaf&iacute;os que est&eacute;n cerca del usuario y enviarle notificaciones. Adem&aacute;s, as&iacute; tambi&eacute;n EcoHeroes podr&aacute; asegurar que el usuario est&aacute; realizando el desaf&iacute;o desde el lugar solicitado. Si el usuario no tiene activado el servicio de localizaci&oacute;n, no podr&aacute; realizar desaf&iacute;os de EcoHeroes.</p>
<p>Por este acto, el usuario entiende y autoriza a EcoHeroes para acceder a sus datos de localizaci&oacute;n.</p>
<strong>D. Conocimiento y aceptaci&oacute;n de los T&eacute;rminos y Condiciones.</strong>
<p>Ser&aacute; requisito necesario para la realizaci&oacute;n de una tarea o beneficio y la adquisici&oacute;n de la recompensa correspondiente, la aceptaci&oacute;n de los presentes T&eacute;rminos y Condiciones, los cuales se entender&aacute;n conocidos y aceptados por el usuario cuando se seleccione la opci&oacute;n "aceptar" indicada en el recuadro creado para este fin, y cuya selecci&oacute;n ser&aacute; requisito previo de la App para ingresar / realizar cualquier desaf&iacute;o. EcoHeroes no aceptar&aacute; ni procesar&aacute; desaf&iacute;os sin que el usuario declare previamente conocer y aceptar los T&eacute;rminos y Condiciones de la aplicaci&oacute;n y de las tareas particulares que se encargan, manifestando expresamente su acuerdo con dichos T&eacute;rminos y Condiciones.</p>
<strong>E. Registro de usuario y clave secreta.</strong>
<p>El usuario, para poder ingresar en la App y ejecutar las tareas encomendadas, deber&aacute; registrarse como tal, mediante un nombre &uacute;nico de usuario y una contrase&ntilde;a asociada que le permitir&aacute; el acceso personalizado, confidencial y seguro. El usuario tendr&aacute; la posibilidad de cambiar la contrase&ntilde;a, para lo cual deber&aacute; seguir el procedimiento establecido en la App.</p>
<p>EcoHeroes velar&aacute; por el mantenimiento de la confidencialidad de la contrase&ntilde;a del usuario, la cual le permitir&aacute; revisar desaf&iacute;os disponibles, ejecutar dichos desaf&iacute;os, revisar el historial de desaf&iacute;os realizados y su estado de aprobado o rechazado, revisar y actualizar sus datos de la cuenta, canjear sus puntos, enviar y recibir mensajes a los encargados de EcoHeroes y obtener informaci&oacute;n. Dicha clave es de uso personal y su entrega a terceros sin la autorizaci&oacute;n previa de EcoHeroes, no involucrar&aacute; responsabilidad para &eacute;sta &uacute;ltima.</p>
<p>El usuario al momento de registrarse, debe declarar que toda la informaci&oacute;n suministrada es verdadera, completa y precisa y que autoriza el uso de dicha informaci&oacute;n en los t&eacute;rminos del art&iacute;culo 4 de la Ley N&ordm; 19.628 sobre Protecci&oacute;n de la Vida Privada o Protecci&oacute;n de Datos de Car&aacute;cter Privado.</p>
<p>La persona que se registra autoriza expresamente a EcoHeroes para que proceda a incluir en un fichero automatizado los datos de car&aacute;cter personal que figuran en los campos del formulario, por resultar necesarios para la adecuada prestaci&oacute;n de sus servicios, tales como:</p>
<p>(A) Realizar an&aacute;lisis estad&iacute;sticos.</p>
<p>(B) Dar cumplimiento a los requisitos de contabilidad, facturaci&oacute;n y auditor&iacute;a de EcoHeroes.</p>
<p>EcoHeroes es responsable de mantener la confidencialidad de los datos proporcionados por el usuario a efectos del ejercicio de los derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n y oposici&oacute;n previstos en la Ley, accediendo el usuario a que sean utilizados de conformidad con la Ley y con lo dispuesto en estos T&eacute;rminos y Condiciones.</p>
<p>Asimismo, al registrarse, el usuario autoriza expresamente la comunicaci&oacute;n de dichos datos a terceros consistentes exclusivamente en los proveedores de servicios asociados a EcoHeroes y/o clientes de Comercializadora Brera SpA, &uacute;nicamente cuando dicha comunicaci&oacute;n resulte necesaria para la adecuada prestaci&oacute;n de los servicios que se contraten, respetando en todo momento la legislaci&oacute;n en vigor.</p>
<p>El usuario da su consentimiento expreso para recibir comunicaciones electr&oacute;nicas con publicidad y novedades comerciales de EcoHeroes y de los encargos que promociona conforme nuestra Pol&iacute;tica de Privacidad, y podr&aacute; optar por no seguir recibiendo dichas comunicaciones d&aacute;ndose de baja y comunic&aacute;ndolo oportunamente a EcoHeroes solicit&aacute;ndolo a contacto@ecoheroes.cl.</p>
<strong>F. Procedimiento para hacer uso de la aplicaci&oacute;n m&oacute;vil.</strong>
<p>En los encargos ofrecidos por medio de la App, el consentimiento s&oacute;lo se entender&aacute; formado cuando el usuario haya tenido previamente un acceso claro, comprensible e inequ&iacute;voco de las condiciones generales del mismo y la posibilidad de almacenarlo o imprimirlo, en virtud del art&iacute;culo 12 A de la Ley N&deg;19.496 sobre Protecci&oacute;n al Consumidor. Para cumplir lo anterior, EcoHeroes informar&aacute; al usuario en la App, de manera inequ&iacute;voca y f&aacute;cilmente accesible, los pasos que deben seguirse para realizar un encargo e informar&aacute; sobre los t&eacute;rminos y condiciones de cada desaf&iacute;o en particular.</p>
<p>Se deja expresa constancia de que la sola visita de la App EcoHeroes no impone al usuario obligaci&oacute;n alguna, a menos que haya aceptado en forma inequ&iacute;voca y expresa las condiciones ofrecidas por EcoHeroes.</p>
<p>Una vez perfeccionado el registro, EcoHeroes enviar&aacute; al usuario confirmaci&oacute;n escrita de su registro y de los t&eacute;rminos y condiciones de uso de la App. &Eacute;sta podr&aacute; ser enviada por v&iacute;a electr&oacute;nica o por cualquier medio de comunicaci&oacute;n que garantice el debido y oportuno conocimiento del usuario, el que se le indicar&aacute; previamente.</p>
<strong>G. Procedimiento de canje de recompensas por los usuarios.</strong>
<p>Los usuarios que hayan realizado desaf&iacute;os recompensados y luego que &eacute;stos hayan sido validados por el equipo de EcoHeroes, podr&aacute;n canjearlos seg&uacute;n las condiciones se&ntilde;aladas en cada cup&oacute;n.</p>
<ol type='1'>
<li>Cupones de descuento: EcoHeroes entregar&aacute; el cup&oacute;n de descuento ofrecido al usuario por la app dentro de 24hrs desde que el desaf&iacute;o fue realizado por el usuario y validado por EcoHeroes. La vigencia de canje del cup&oacute;n depender&aacute; de las condiciones ofrecidas por las empresas patrocinadoras, informaci&oacute;n que ser&aacute; comunicada al usuario a trav&eacute;s de la app.</li>
<li>Cupones de plantaci&oacute;n de &aacute;rboles: EcoHeroes entregar&aacute; el cup&oacute;n de plantaci&oacute;n de &aacute;rboles ofrecido al usuario por la app dentro de 24hrs desde que el desaf&iacute;o fue realizado por el usuario y validado por EcoHeroes. El canje del cup&oacute;n deber&aacute; ser realizado por el usuario a trav&eacute;s de la p&aacute;gina web de la fundaci&oacute;n One Tree Planted, <a href="https://onetreeplanted.org/products/plant-trees">https://onetreeplanted.org/products/plant-trees</a>, o bien, el usuario puede solicitar el canje a trav&eacute;s del equipo de EcoHeroes, escribi&eacute;ndonos a <a href="mailto:contacto@ecoheroes.cl">contacto@ecoheroes.cl</a>. Luego de canjeado el cup&oacute;n por &aacute;rboles en el lugar escogido entre las opciones ofrecidas por la ONG, el usuario recibir&aacute; un certificado con el detalle de su donaci&oacute;n a su email.</li>
<li>Puntos de canje: EcoHeroes entregar&aacute; la cantidad de puntos ofrecidos al usuario por la app dentro de 24hrs desde que el desaf&iacute;o fue realizado por el usuario y validado por EcoHeroes. En la secci&oacute;n de su cuenta podr&aacute; ver los puntos acumulados a la fecha, pudiendo ser canjeados cuando estime conveniente en productos, servicios, experiencias y giftcards ofrecidas por PuntosPoint, empresa asociada a EcoHeroes. Los puntos acumulados podr&aacute;n ser canjeados dentro de 1 a&ntilde;o a partir de la fecha del &uacute;ltimo puntaje obtenido. Si el usuario no registr&oacute; nuevos desaf&iacute;os con recompensas en puntos dentro de 365 d&iacute;as, sus puntos acumulados quedar&aacute;n invalidados. En caso de canjear los puntos por giftcards, estas tendr&aacute;n una vigencia de un a&ntilde;o y medio (547 d&iacute;as) desde la fecha en que fueron canjeadas por el usuario, esto es, desde la fecha en que se descontaron los puntos desde la cuenta del usuario para obtener la giftcard de cierto monto en pesos de un comercio asociado.</li>
<li>Hojas de experiencia (): Cada cierto tiempo, EcoHeroes realizar&aacute; sorteos de diversos productos que son amigables con el medio ambiente, por los cuales los usuarios podr&aacute;n concursar a cambio de sus &ldquo;hojas de experiencia&rdquo; que tengan acumulados y cumplan con el m&iacute;nimo requerido.</li>
</ol>
<p>EcoHeroes se reserva el derecho de no recompensar con puntos, cupones de descuento, cupones de &aacute;rboles y hojas de experiencia, a cualquier usuario que proporcione informaci&oacute;n falsa en su registro o en el cumplimiento de un desaf&iacute;o, as&iacute; como cuando incumpla cualquiera de las obligaciones de todo usuario descritas en la cl&aacute;usula H siguiente.</p>
<strong>H. Obligaciones de los usuarios.</strong>
<ol type='1'>
<li>Al aceptar un desaf&iacute;o, el usuario se compromete a realizarlo de la manera m&aacute;s fiel y honesta posible, de acuerdo a las instrucciones particulares de cada encargo.</li>
<li>El usuario asume el compromiso de no identificarse como trabajador de EcoHeroes frente a terceros, a excepci&oacute;n de aquellos desaf&iacute;os en que se detalle expl&iacute;citamente lo contrario.</li>
<li>Queda estrictamente prohibido a los usuarios infringir la ley, perturbar el orden y seguridad, o en general, realizar cualquier acto ilegal, arbitrario o contrario a la buena fe, durante o con ocasi&oacute;n de la ejecuci&oacute;n de la tarea.</li>
<li>El usuario debe velar por su salud y seguridad en la ejecuci&oacute;n de un encargo. El usuario deber&aacute; suspender de inmediato la ejecuci&oacute;n de un desaf&iacute;o si ve que en su ejecuci&oacute;n pone en peligro su integridad f&iacute;sica o ps&iacute;quica, o bien se expone a amenazas, agresiones o golpes que puedan exponerle a riesgos innecesarios.</li>
</ol>
<strong>I. Responsabilidad de EcoHeroes o la Empresa.</strong>
<p>La Empresa o EcoHeroes no se hacen responsables por los perjuicios que pueda sufrir un usuario durante la realizaci&oacute;n de una tarea, sea por robos, da&ntilde;os personales o da&ntilde;os a la propiedad.</p>
<p>Del mismo modo, la Empresa o EcoHeroes no se responsabiliza por actos de sus usuarios que puedan provocar perjuicios a terceros, durante o con motivo de la ejecuci&oacute;n de un desaf&iacute;o. El usuario es el exclusivo responsable tanto de la ejecuci&oacute;n del desaf&iacute;o como de las gestiones y operaciones que realice el usuario para la ejecuci&oacute;n del mismo.</p>
<p>Asimismo, la responsabilidad por los costos, gastos, derechos y eventuales multas derivados de dichas gestiones y operaciones, corresponde &uacute;nica y exclusivamente al usuario.</p>
<p>En el supuesto de que EcoHeroes o su cliente mandante fuesen condenados como responsables civilmente por cualquier da&ntilde;o o perjuicio ocasionado por el usuario, el &uacute;nico responsable de las indemnizaciones ser&aacute; el usuario que provoc&oacute; el da&ntilde;o o perjuicio, quien deber&aacute; mantener indemne a EcoHeroes de todo perjuicio y resarcir toda indemnizaci&oacute;n a la que sea condenada por este concepto.</p>
<p>La Empresa o EcoHeroes no se hacen responsables por la comisi&oacute;n de il&iacute;citos en el desempe&ntilde;o de un desaf&iacute;o. En caso de que esto ocurra, EcoHeroes podr&aacute; cancelar inmediatamente la cuenta del usuario, reteniendo cualquier canje pendiente. Todo esto, sin perjuicio de las dem&aacute;s acciones civiles, penales, y/o de cualquier naturaleza que pueda ejercer conforme a la legislaci&oacute;n vigente.</p>
<strong>J. Validez de las ofertas de desaf&iacute;os contenidas en la App.</strong>
<p>Las recompensas de los desaf&iacute;os disponibles en la App de EcoHeroes, s&oacute;lo tendr&aacute;n vigencia y aplicaci&oacute;n temporal, limitada y breve mientras aparezcan publicados en &eacute;l y no ser&aacute;n necesariamente aplicables a otros canales que pudiese utilizar EcoHeroes, tales como redes sociales u otros.</p>
<p>El usuario declara y entiende que las ofertas de recompensa y condiciones por desaf&iacute;o pueden cambiar durante el transcurso del d&iacute;a. Sin embargo, se respetar&aacute;n siempre las condiciones ofrecidas y debidamente aceptadas para cada desaf&iacute;o.</p>
<ol>
<strong>K. Derecho de propiedad.</strong>
</ol>
<p>Todos los contenidos, marcas, logos, dibujos, etc. que figuran en EcoHeroes, se hallan protegidos por los derechos de propiedad intelectual e industrial que son expresamente reservados para EcoHeroes, sus empresas relacionadas o, en su caso, por las personas o empresas que figuran como autores o titulares de los derechos. La violaci&oacute;n de los anteriores derechos ser&aacute; perseguida de conformidad con la legislaci&oacute;n vigente.</p>
<p>Por lo tanto queda prohibida la reproducci&oacute;n, explotaci&oacute;n, alteraci&oacute;n, distribuci&oacute;n o comunicaci&oacute;n p&uacute;blica por cualquier t&iacute;tulo o medio de la totalidad de los contenidos en la App para usos diferentes de la leg&iacute;tima informaci&oacute;n o contrataci&oacute;n por los usuarios de los servicios ofertados. En todo caso, ser&aacute; necesario el consentimiento previo por escrito de EcoHeroes.</p>
<p>El usuario reconoce que cualquier infracci&oacute;n a esta obligaci&oacute;n genera un grave perjuicio a EcoHeroes.</p>
<strong>L. Procedimiento de reclamos.</strong>
<p>Para realizar cualquier reclamo por actos o contratos ejecutados o celebrados a trav&eacute;s de EcoHeroes, la Empresa seguir&aacute; el siguiente procedimiento:</p>
<p>(a) El usuario debe enviar su presentaci&oacute;n o reclamo al correo electr&oacute;nico contacto@ecoheroes.cl junto con todos los antecedentes que respalden el reclamo y una narraci&oacute;n de lo ocurrido, indicando en t&eacute;rminos claros y precisos la soluci&oacute;n esperada, con el fin de dar una respuesta lo m&aacute;s r&aacute;pida posible.</p>
<p>(b) EcoHeroes revisar&aacute; el reclamo, y la respuesta ser&aacute; enviada al mismo correo electr&oacute;nico del reclamo, dentro del plazo de 30 d&iacute;as a contar de la recepci&oacute;n de los antecedentes. En caso de requerir un plazo adicional, ello le ser&aacute; informado al usuario.</p>
<p>&nbsp;</p>
</div>
      """,
);
